# Generated by Django 5.1 on 2024-08-31 12:56
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20240831_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='access_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
